// MOVIES
export const MOVIES_LOADING = 'MOVIES_LOADING';
export const MOVIES_ADD = 'MOVIES_ADD';
export const MOVIES_FAILED = 'MOVIES_FAILED';

// AUTH
export const AUTH_TOKEN_REQUEST_INPROGRESS = 'AUTH_TOKEN_REQUEST_INPROGRESS';
export const AUTH_TOKEN_REQUEST_OK = 'AUTH_TOKEN_REQUEST_OK';
export const AUTH_TOKEN_REQUEST_FAILED = 'AUTH_TOKEN_REQUEST_FAILED';

export const AUTH_INPROGRESS = 'AUTH_INPROGRESS';
export const AUTH_OK = 'AUTH_OK';
export const AUTH_FAILED = 'AUTH_FAILED';